apiVersion: v1
kind: Pod
metadata:
    name: mongo-pod
    labels:
        app: microservice-libreria
        name: mongo-pod
spec: 
    containers:
    - name: mongo
      image: mongo:5.0.7
      command:
        - /bin/bash
        - -c
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: ""
        - name: MONGO_INITDB-ROOT_PASSWORD
          value: ""
      ports:
        - containerPort: 27017