apiVersion: v1
kind: Pod
metadata:
    name: mongo-pod
    labels:
        app: microservice-libreria
        name: mongo-pod
    spec: 
        containers:
        - name: mongomongo:4.2.12
          command:
          - /bin/bash
          - -c
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "oarcaya1972"
          - name: MONGO_INITDB-ROOT_PASSWORD
            value: "Caro2018*."
          ports:
            - containerPort: 27017