apiVersion: v1
kind: Pod
metadata:
    name: mongo-pod
    labels:
        app: microservice-libreria
        name: mongo-pod
spec: 
    containers:
    - name: mongo
      image: mongo:5.0.7
      command:
        - /bin/bash
        - -c
      ports:
        - containerPort: 27017