apiVersion: apps/v1
kind: Deployment
metadata:
	name: mongo-deploy
	labels:
	  name: mongo-deploy
		app: microservice
spec:
    replicas: 1
	  selector:
		  matchLabels:
			  app: microservice-libreria
			  name: mongo-pod
	    template:
		    metadata:
          name: mongo-pod
          labels:
            app: microservice-libreria
            name: mongo-pod
          spec: 
            containers:
              - name: mongo
                image: mongomongo:4.2.12
                command:
                  - /bin/bash
                  - -c
                env:
                  - name: MONGO_INITDB_ROOT_USERNAME
                    value: "oarcaya1972"
                  - name: MONGO_INITDB-ROOT_PASSWORD
                    value: "Caro2018*."
                ports:
                  - containerPort: 27017